apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{values.app_name}}
  description: Python application for demonstration purposes, named ${{values.app_name}}
  # Example for optional annotations
  annotations:
    github.com/project-slug: monvillanueva/${{values.app_name}}
spec:
  type: service
  owner: development
  lifecycle: experimental